language: node_js
branches:
  only:
    - master
env:
  global:
    - NODE_ENV=development
    - GH_URL=https://github.ibm.com
    - GH_PREFIX=/api/v3
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "9"

before_install:
  - sudo apt-get install git
  - npx git+https://$GH_TOKEN:x-oauth-basic@github.ibm.com/watson-finance/npm-login-artifactory.git -e paul.sachs@ibm.com -p $ART_TOKEN -n na.artifactory.swg-devops.com -r "@fss=>ip-wfss-npm-virtual" -xzq
  - npx git+https://$GH_TOKEN:x-oauth-basic@github.ibm.com/watson-finance/npm-login-artifactory.git -e paul.sachs@ibm.com -p $ART_TOKEN -n na.artifactory.swg-devops.com -r "@fss=>ip-wfss-npm-local" -xzq

install:
  - npm install

script:
  - npm run test:prod && npm run build && npm run build-storybook

deploy:
  - provider: pages
    github-url: github.ibm.com
    local-dir: storybook-static
    skip-cleanup: true
    github-token: $GH_TOKEN
    keep-history: false
  - provider: script
    skip_cleanup: true
    script: npm run semantic-release
