language: node_js
env:
  global:
    - NODE_ENV=development
    - secure: qP8k+DxeWWHadliQkfFpN+t4UQkxNQqvcomAOemDYkctMq9yzjt20uOAdd2HetiHYjN/grrd7iniIL9b82nUwiTrQ2r2tL3PQ5qNCeodGsjB0hwEPnSHTXxbaP7C4f4EPPMi+1/2mPsfcTcSqGEvdB8gtW0bsy5p/w4qsJLNWAo2ThpwmLxpQu17wofJjORwglsx40rJJIC8/7sYhlshYXuEZ7Fs8k7h35lwXdh+jrNXm1EdU/VjzL7nG4DA+ZY6Wo9M1uBCUJVMPBNpjaHL7bCb/YC1eVvgHJwdFoRkCiYo2fmFns742p4yywj8FhUiyEQXQMZeu6wJcn7kPIf7S5X7hUp4HUOjMI3VB6YCcqRA1M8Pogko4oq79WLTdzUPwTwUM6+7S1GhpI82aIb1bLzEb//3lPwTez6LBgDuy3QCoa5+iQnaU+B6HChu6/dQBPIbd9IhrIEb78YdgdPQNsa7N2psiT+bqP19LUGKCmJv3P9IoVe+QecrTUDQ/CA5uPv9TAaJ1LSFOjGC18McdEa2XR+GhvZEEveL2tKLH1+D2CEf8SlH9/EfW7EVF4c0te027UY3fGijJ6xFAb99A0y1fO9EOsBVx43QWKwSogfHaIA7HAMC3D+C3uoyUB/qPJXlpfiY13n7jjRDBfeOka1nu0NM7AYmwCRxU79pyk8=
    - secure: vsAATiD7flQB3Yvt4jSlV8kyrlXPJWMx+ICrnHHLj71qWKqH7TdWkFlJ6J4YVAWit8VmvOx/DiU/r+GE9vuHwvDIPI0MnNh07y8yFosZhDB2xLa2ws3F4+t+vYbydxrs+Iu+sdFGDm4D68jtZISWaOcjB6pcFLuChCFvzOQKXonZ5YRNbAtTSJ3teoupHPYkielJ8OMwtmTMDZFCD1quSwBHzoJ1JgnMTqtTfWOM3ZwKFAged/SLMlakyMZ3E9DXcOLM0m0ZvLKwHsQN2M4RLEd/jI5Q+SHxrdw3k9g1Ynq8CdpfgPevgsa705V2+GpBfiMJXxHZVZxQnNwmcsTBJ3pb5g1g12DUiP36a7hIS8A+qtOTcFXVIIb279UiXH1wWcgG/07QfaZ4NaJGydz9bvj7vh2gWjMpKtBRsCvbwo7UlCKb0O30eMNTyUcRQ7B6sQuwF+fwHMQ8oblmwwshbw2BHA/wjWnhqNWuCGZ2TfyEP9w/3ozxtzuh1uYVLSdE+RLy1xUFTrtTJBOazcmwZ3FrgyYKlEJXq2UldgxtMwCkWM/IT1CsYibX7IXto+ZuC0+kyUhY8ZfIk2vVlH07rSQo/IdNifkQfa4qJYegnDUu0BwaHyPVtM9w0pexNl2jqLCLnUih7jaD7f+P6ggL2hhMYz6ISi1mpsIBxLK4PYI=
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
  slack:
    on_success: never
    on_failure: always
    rooms:
      - secure: mPtdA6/mnnmRKOg/Hd4JFPjJsmuImQFCAjW6BVAGMjTjiUYF1OR98aj9V8LNOfSNGGXzhGgK2pztSHIPonAKivED9N0gdcMvoPz+qjSoDtt25bsIkywZsP+eKczWy1h2K2Dorv6bZRgQz4JrWpTLOcgl6ALg+wa+6qMsEkEf1L+IxshgmeK639n2sgMVYrU/mGCM7MdoQoE8Y0Uz8VyUHYXMQkL9S5xNOWrkU+NNGyfFxOf0E8RREgXL87N4Xffnir8+ARj10/iiep1rSsJbZqY91Vp4GvD85VSHOmbhkXBqD76CuylUcV74cy3ubgY2Le4haagrq7+CnW18X/6xv+S0X0Exoe/QwuWjeHTdwf+1fhbPjbTtKQrfENAm7z2jGrpO2J989HjqN1jbjJPpJ0JoeXQUuKDIiVdUIos3Any8mOSI+Rq+mzXI/UyIC1hWi/9+sxauPFz+XwrGoN5CQnLtJ2f9iQJle/xc5efXhYYfpE1jgMyVgD6GGC2t2YDVPIEzvJ4I6rQ7oU3iN5/ZwQQhU/Q6CgCtST4MUbQOPdGn3UhpKW2ShLLf29ME0xq96ckrKWkcXaxtWZt1efwOpAUV4hu49QyxQQE3GlGXvu0eCHvUIDCZzxeSuWjk/NOmotn/qx2yjjtoPByDUHW352hBJ4bl7OW8thkcQsI8860=
node_js:
  - "9"
before_install:
  - npm install -g now
install:
  - npm install
script:
  - npm run test:prod
  - npm run build
  - npm run build-storybook
deploy:
  - provider: pages
    local-dir: storybook-static
    skip-cleanup: true
    github-token: "$GH_TOKEN"
    keep-history: false
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: npm run semantic-release
    on:
      branch: master
