language: node_js
env:
  global:
    - NODE_ENV=development
    - GH_URL=https://github.ibm.com
    - GH_PREFIX=/api/v3
    - secure: "f5bKeWQ/KlXW/JWKeBxB0HYbLCBeMeS96O+/CNnGXWd2XWwtupn68VzPCnENkFsvwuazeQHQwMRb2wAg0jZmqE4dH7Ewu2DM7GRc8z0fFtFkIlpXrVTe+ruw44tYRDSIG+u7gN9Jt7m52gslG3E+iIlj6htg9Vd+zdjt2zqYojxUqHECe+Lv+tfp2H53JrrhHZQSuqg4bhgOzW5WrMWbYpZM1YBDQp/hpBGHISo6cfoR9Wwb7Iy6+N+3AcQmuxV4sskXgqpxR1btqPF9qncwfqbygVvmpQNGszSKsufo6TxmlfaUdCByFr1WBuQdIHHlgpigCUf+AwKtc5inC4OZ6WBSfvDQQhu+IVvXg9N8uf8wg9qu4npHLtZOmNVHiL0tCIluucHisk9J80HjCr3izfKFTwoECNh56JN+Be/6SYtmAVi5J7vwjB13BhCqlneXFLQmPBojuo6MMYuS1L/vr2EmJz1gwLqN29qtdkU7Jz2HD0u+yhxA1IQyh/uZiZN/w2+g1xpJC8y5GEtlEw0jtTs16+2DvMFYsRtg8T3w0PmMgs4lfCVVc8cHwfb7BjxdDoovKkOOT/4ahdAtaoaBEvKjRQjC88HigS1DNpJ+vq5AhIzNznhp5Pn45ntYSaBX1wjeo0Rgi6+Ti4S2HXsoRg+wMaNn9AhbPu065oihU64=" # NOW_TOKEN
cache:
  directories:
    - node_modules
branches:
  only:
    - master

notifications:
  email: false
  slack:
    on_success: never
    on_failure: always
    rooms:
      - secure: inllTuJEx6NZnnOsHQ1auDuNdtpA3utKry/Ny0DpzM3DzRg0xpJ2n4QAFxu9wE4ud7HUZZiZE166mb//w7J5/peAhKuwOQ0F3YUzCyBIJcOV7FpTRvoimq825g7oa84t12QirB1PKxaeGmrSu4868JsK6FAqrrFYY12yNIEroqToTDSYj0AJuovKMXVnosuB/8U+3nWZY3PRjye+92C/0XFF3KB7VYFECqQiq1hPFJ7Jmw+S66sy3/A/jUYRo/+6DUJk0QwcDki0yHTwNCnJhoQvQRh3HWOW4a/WjxvoTfKWlJL4Ey2xzb9osUtqY9h+aI9m/8UA/xu9eigeWWscUhimrOejF25sSCYx+cM4A9O1brzu6saj4XOws9K0SdZmogmqdfh3eE7Jb+YGfFvGQdhwcjDaItEhORpEMukmIiejGsz34NFSAMRjG0fPXXCXJykFBQ8Yn4wH7wFrMuXo3AzOwvmqYifObKX/APo7vtQtuygfzvWiLf53kvUBK/w77GLE7UObEDJAAURmXbCkTTThWmqOJa2ehhOHxZ67pgMjkCOXj2mFag/PgrFiQltW06CXmbbVNyT2ahZ3UsCOMQrN5ThU7PXUveFwc+pW3uzCVGom1Dq7kuvfDiIxAnggRu5KO4SUrnctSCnU1geGBBpmpJ+r74FYJhKBx2H3GyI=

node_js:
  - "9"
dist: xenial

before_install:
  - npx git+https://$GH_TOKEN:x-oauth-basic@github.ibm.com/watson-finance/npm-login-artifactory.git -e paul.sachs@ibm.com -p $ART_TOKEN -n na.artifactory.swg-devops.com -r "@fss=>ip-wfss-npm-virtual" -xzq
  - npx git+https://$GH_TOKEN:x-oauth-basic@github.ibm.com/watson-finance/npm-login-artifactory.git -e paul.sachs@ibm.com -p $ART_TOKEN -n na.artifactory.swg-devops.com -r "@fss=>ip-wfss-npm-local" -xzq
  - npm install -g now

install:
  - npm install

script:
  - npm run test:prod && npm run build && npm run build-storybook

# uncomment this once we can deploy prs
# after_success:
#   - scripts/prDeploy.js

deploy:
  - provider: pages
    github-url: github.ibm.com
    local-dir: storybook-static
    skip-cleanup: true
    github-token: $GH_TOKEN
    keep-history: false
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: npm run semantic-release
    on:
      branch: master
